### ISSUE TITLE
API incompatibility with meteor/http default timeout

### ISSUE THREAD

**Issue by sree-qlp** [jankapunkt/meteor-http#6]
Hi,

I am not sure if the library is still maintained. We used this to migrate to latest meteor in our projects without changing much syntax for http calls except the http timeout setting.

With the Abort Controller implementation in this library, the default timeout is set to 90s.
But, the original meteor/http library does not have a default timeout at all.
Refer - https://docs.meteor.com/api/http.html#HTTP-call

> timeout Number
Maximum time in milliseconds to wait for the request before failing. There is no timeout by default.

Please update this in the docs regd. preserving original API functionality, or remove the default timeout setting.

Thanks!

**Comment by jankapunkt** [comment]
Hi @sree-qlp this package is still maintained. I could think of using `-1` to indicate no timeout and use this as a default value, leaving the option to still pass a timeout, if desired. Would you help me with reviewing the PR?

**Comment by sree-qlp** [comment]
Hey @jankapunkt thank you for the response. Absolutely! happy to help :)

**Comment by jankapunkt** [comment]
@sree-qlp please review #7 thank you!

**Comment by jankapunkt** [comment]
published as `2.3.0`
